### ISSUE TITLE
Device Startup Error

### ISSUE THREAD

**Issue by MG665** [Buck3ts41/KingCU.cc-SeaOfThieves-Cheat#2]
Getting "Device Startup Error" when running the .exe

**Comment by Buck3ts41** [comment]
Just make sure to start it when you are in the press a key to start screen.
If you get pdevice error restart the program a few times

**Comment by AWL-Gaming** [comment]
> Just make sure to start it when you are in the press a key to start screen. If you get pdevice error restart the program a few times

I don't get any such screen, my game goes to this immediately after I start it (and after the intro video) 
![image](https://user-images.githubusercontent.com/22678541/193627550-d0b293e1-6c15-4fe6-a11c-c41d37f2fc24.png)

**Comment by MG665** [comment]
> Just make sure to start it when you are in the press a key to start screen. If you get pdevice error restart the program a few times

I don't get any such screen, my game goes to this immediately after I start it (and after the intro video)
![image](https://user-images.githubusercontent.com/13345045/193627898-94928581-76a1-4036-8534-c51ee6a0f0bd.png)
There is some type of an error on the Windows Event Viewer:

```
Faulting application name: SotExternalESPv3.4.6_[unknowncheats.me]_.exe, version: 0.0.0.0, time stamp: 0x63385d1b
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000000000000
Faulting process id: 0x42f0
Faulting application start time: 0x01d8d7439f37f4cc
Faulting application path: D:\Downloads\SotExternalESPv3.4.6_[unknowncheats.me]_.exe
Faulting module path: unknown
Report Id: d96f41eb-fc51-481e-87a6-9f045014b556
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by MG665** [comment]
Ah it worked, I've redownloaded the github file instead of the UC one.
