### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LeandroPaim** [Buck3ts41/KingCU.cc-SeaOfThieves-Cheat#4]
hello I already downloaded the compiled version and opened it right in the menu that asks to click to start the game but nothing happens nothing opens in the game and trying to download the source to compile I get a lot of errors do not know what to do before I received this error Cannot open include file: d3dx9.h: No such file or directory could fix but now give other errors

**Comment by LeandroPaim** [comment]
I already solved it and now it is working normally, the menu appeared, thanks for the incredible cheat. I would like to know if you intend to add aimbot for the guns and the cannon or some kind of triggerbot?

**Comment by Buck3ts41** [comment]
i already added aimbot, but is too risky for public release. Maybe a triggerbot

**Comment by cooldude315** [comment]
> i already added aimbot, but is too risky for public release. Maybe a triggerbot

can you upload that so i can look into it?
