### ISSUE TITLE
While compiling the latest release the following error occurs

### ISSUE THREAD

**Issue by JhonTXdons** [Buck3ts41/KingCU.cc-SeaOfThieves-Cheat#6]
Eccezione generata in corrispondenza di 0x00007FFF598F1597 (vcruntime140d.dll) in __.exe: 0xC0000005: violazione di accesso durante la scrittura del percorso 0x000000000000000F.

![image](https://user-images.githubusercontent.com/42693127/194554061-a82ad130-e366-4859-8d31-a082853b1bb8.png)

**Comment by Buck3ts41** [comment]
Just uncheck the box below the error and make sure that you have the repositories setting right matched

**Comment by JhonTXdons** [comment]
even cheking the box doesn't resolve the issue. Repositories setting are matched

**Comment by cooldude315** [comment]
> even cheking the box doesn't resolve the issue. Repositories setting are matched

did you fix the issue, if so how?

**Comment by Buck3ts41** [comment]
try by importing each module on visual studio
