### ISSUE TITLE
Crashes after i load into game

### ISSUE THREAD

**Issue by cooldude315** [Buck3ts41/KingCU.cc-SeaOfThieves-Cheat#7]
How do i fix this, the cheat crashes after i load into the game

**Comment by cooldude315** [comment]
https://cdn.discordapp.com/attachments/834803478085369856/1036372280848162957/unknown.png

**Comment by cooldude315** [comment]
![image](https://user-images.githubusercontent.com/117041200/198900135-fc564bf0-5217-4efd-806b-7c3e5706a421.png)

**Comment by Buck3ts41** [comment]
i suggest downloading the release

**Comment by cooldude315** [comment]
> i suggest downloading the release

i think it needs a offset change atm

**Comment by cooldude315** [comment]
i fixed the crash it just doesnt load anything like it doesnt show the ships or esp

**Comment by cooldude315** [comment]
@Buck3ts41 by the way for the aimhelper you would need to use valid angles so you dont get banned

**Comment by Buck3ts41** [comment]
Working on aimbot, the crashing reason was the decimal offsets :)
