### ISSUE TITLE
How to start and update?

### ISSUE THREAD

**Issue by kakzk** [Buck3ts41/KingCU.cc-SeaOfThieves-Cheat#8]

**Comment by Buck3ts41** [comment]
see the how to update.txt

**Comment by kakzk** [comment]
and where it is? i dont see it sorry

**Comment by Buck3ts41** [comment]
check now :)

**Comment by kakzk** [comment]
great, thanks. and how do i compile the cheat to work? what files, what program, if you can bring any help i would be very thankful

**Comment by Buck3ts41** [comment]
the idle is visual studio, but if you have no experience with it, i suggest you to wait until i post the updated cheat in release

**Comment by kakzk** [comment]
okay, thank you very much, and great work!

**Comment by kakzk** [comment]
sorry to bother again xD,  im not being able to make it find the offsets, i try it with everything, even putting every file of the carpet. im using the [DougTheDruid](https://github.com/DougTheDruid) offsets. I know im being annoying but i want to learn so in the future i dont need to do all this questions, sorry <3

**Comment by Buck3ts41** [comment]
DougTheDroid offsets finder won't be able to extract all the offsets needed for this cheat, tomorrow i will upload the new sdk so you can use the offsets finder that is in the update folder. Tomorrow i will update the cheat. 
I suggest you to try to start with [DougTheDruid](https://github.com/DougTheDruid) python cheat if you want to learn, c++ cheat are much more difficult

**Comment by kakzk** [comment]
okay, again thank you so much. i will wait for the update
